# Python HITMIX Example: Graph Analysis

In this notebook, we demonstrate the use of HITMIX for computing _hitting time moments_ for a set of vertices in a graph.

```
Copyright 2021 National Technology & Engineering Solutions of Sandia,
LLC (NTESS). Under the terms of Contract DE-NA0003525 with NTESS, the
U.S. Government retains certain rights in this software.
```

## Authors
* Danny Dunlavy (dmdunla@sandia.gov)

## Load package dependencies

In [1]:
# Hitting time moment computation
import hitmix

# Data objects
import numpy as np
from scipy.sparse import csr_matrix, coo_matrix

# Plotting
import matplotlib.pyplot as plt
%matplotlib inline

## Example 1: Single-component Graph

This graph has 5 vertices and 1 connected component. 

Vertices that are part of the hitting set will have hitting time moment values of 0.

<img align="left" src="graphviz/example-1.png" height="200"/>

In [2]:
# create adjacency matrix
n1 = 5
row1 = np.array([0, 1, 1, 2, 3])
col1 = np.array([1, 2, 3, 4, 4])
data1 = np.array([1, 1, 1, 1, 1])
A1 = coo_matrix((data1, (row1, col1)), shape=(n1, n1))
A1 = A1 + A1.T
print(f"Adjacency matrix (A1) =\n{A1.todense()}")

Adjacency matrix (A1) =
[[0 1 0 0 0]
 [1 0 1 1 0]
 [0 1 0 0 1]
 [0 1 0 0 1]
 [0 0 1 1 0]]


In [3]:
# define hitting set indices
omega1 = np.array([0])

In [4]:
# compute hitting time moments
ETm1, cg_info1 = hitmix.hitting_time_moments(A1, omega1)

In [5]:
# view results
print(ETm1)

[[ 0.          0.        ]
 [ 9.         10.58300524]
 [12.         10.95445115]
 [12.         10.95445115]
 [13.         10.95445115]]


## Example 2: Graph with disconnected components

This graph has 5 vertices and 2 disconnected components. 

Vertices that are unreachable from the hitting set will have hitting time moment values of $\infty$.

<img align="left" src="graphviz/example-2.png" height="200"/>

In [6]:
# create adjacency matrix
n2 = 5
row2 = np.array([0, 2, 3])
col2 = np.array([1, 3, 4])
data2 = np.array([1, 1, 1])
A2 = coo_matrix((data2, (row2, col2)), shape=(n2, n2))
A2 = A2 + A2.T
print(f"Adjacency matrix (A2) =\n{A2.todense()}")

Adjacency matrix (A2) =
[[0 1 0 0 0]
 [1 0 0 0 0]
 [0 0 0 1 0]
 [0 0 1 0 1]
 [0 0 0 1 0]]


In [7]:
# define hitting set indices
omega2 = np.array([2])

In [8]:
# compute hitting time moments
ETm2, cg_info2 = hitmix.hitting_time_moments(A2, omega2)

In [9]:
# view results
print(ETm2)

[[       inf        inf]
 [       inf        inf]
 [0.         0.        ]
 [3.         2.82842712]
 [4.         2.82842712]]
